### ISSUE TITLE
Authorization fails when using module with azurerm provider configured to use Service Principal Auth

### ISSUE THREAD

**Issue by elts** [aztfmod/terraform-azurerm-caf-activity-logs#10]
Authorization fails when using module with azurerm provider configured to use Service Principal Auth.
Fails with the following error:
```
Error: Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

  on .terraform/modules/activity_logs/terraform-azurerm-caf-activity-logs-3.0.0/main.tf line 11, in provider "azurerm":
  11: provider "azurerm" {
```

the module will work if I remove provider block from the `main.tf` file.

**Comment by elts** [comment]
Just figured a workaround.
Hashicorp recommends to constrain versions with `terraform` block. 
So swapped `provider` block with `terraform` block, and it fixed the issue. See Pull Request #11 

Tested on:
Terraform: 0.12.24
azurerm provider: 2.13.0

**Comment by arnaudlh** [comment]
Thanks @elts I added it into the vnext branch that will be released this month
